name: BuildTest

on:
  pull_request_target:
    types: [labeled]
    
env:
  NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
  PERSON_ACCESS_TOKEN: ${{ secrets.PERSON_ACCESS_TOKEN }}

jobs:
  lint:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'safe to test')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint # lint 테스트

      - name: Run build
        run: npm run build # build 테스트
