name: Sync dev and main branches

on:
  pull_request:
    branches:
      - dev # dev 붙이려는 PR이 등록 될 때

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      # 원격 레포지토리 체크아웃
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          repository: Codeit-FESI-06-Team2/Project
          ref: dev # 원본 dev 브랜치를 가져옴
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      # 개인 레포지토리 dev 브랜치로 푸시
      - name: Push changes to forked dev branch
        run: |
          git config user.name "KJongHwa"
          git config user.email "dblls0724@naver.com"
          git remote add forked https://github.com/KJongHwa/MoYeoBang.git
          git checkout dev
          git push forked dev --force

      # 개인 레포지토리 main 브랜치로 동기화
      - name: Push changes to forked main branch
        run: |
          git config user.name "KJongHwa"
          git config user.email "dblls0724@naver.com"
          git checkout main || git checkout -b main
          git merge dev --no-edit
          git push forked main --force
